num1=int(input("Enter the valie of number 1"))
num2=int(input("Enter the valie of number 2"))
print("Numbers before swaping")
print("num1 is = ",num1)
print("num2 is = ",num2)
(num1,num2) = (num2,num1)
print("Numbers After swaping")
print("num1 is = ",num1)
print("num2 is = ",num2)
