name=input("Enter the name:")
branch=input("Enter the branch:")
gen=input("Enter the gender:")
clg=input("Enter the college:")
age=int(input("Enter the age:"))
print("\nName:",name)
print("Branch:",branch)
print("Gender:",gen)
print("College:",clg)
print("Age:",age)
